In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
std=sqrt(mean(abs(x-x.mean())**2))
np.std([1,2,3,4])

NameError: name 'sqrt' is not defined

In [3]:
import numpy as np

In [4]:
np.amin([10,29,5,4,2,32,1])

1

In [5]:
np.amax([10,29,5,4,2,32,1])

32

In [7]:
np.mean([10,29,5,4,2,32,1])

11.857142857142858

In [8]:
np.std([10,29,5,4,2,32,1]) 

12.11172479670094

In [9]:
np.var([10,29,5,4,2,32,1])

146.69387755102042

In [10]:
np.ptp([10,29,5,4,2,32,1])

31

In [11]:
np.sqrt([10,29,5,4,2,32,1])


array([3.16227766, 5.38516481, 2.23606798, 2.        , 1.41421356,
       5.65685425, 1.        ])

In [12]:
np.sort([10,29,5,4,2,32,1])

array([ 1,  2,  4,  5, 10, 29, 32])

In [15]:
np.median([10,29,5,4,2,32,1])

5.0

In [19]:
np.average([10,29,5,4,2,32,1])

11.857142857142858

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
np.zeros(4)+5

array([5., 5., 5., 5.])

In [28]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.linspace(1,10,2)

array([ 1., 10.])

In [35]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
np.random.rand(1)

array([0.54884856])

In [38]:
np.random.rand(5)

array([0.55292763, 0.94738264, 0.8942701 , 0.59404215, 0.64905968])

In [39]:
np.random.rand(9)

array([0.23835697, 0.58163286, 0.94910383, 0.96766979, 0.83857509,
       0.93208501, 0.38981781, 0.24290799, 0.0923115 ])

In [42]:
arr=np.random.rand(9)
print(arr)

[0.02505843 0.73301154 0.34874366 0.77457544 0.17980624 0.37327417
 0.73688196 0.83075187 0.64365872]


In [44]:
arr.shape

(9,)

In [45]:
arr.reshape(3,3)

array([[0.02505843, 0.73301154, 0.34874366],
       [0.77457544, 0.17980624, 0.37327417],
       [0.73688196, 0.83075187, 0.64365872]])

In [46]:
print(arr.reshape(3,3))

[[0.02505843 0.73301154 0.34874366]
 [0.77457544 0.17980624 0.37327417]
 [0.73688196 0.83075187 0.64365872]]


In [49]:
arr=np.random.randn(9)

In [50]:
print(arr)

[ 1.52885439 -0.70541734  0.782226    0.23547317 -0.88726736 -1.88929099
 -0.6928929  -0.27013184 -1.16523227]


In [51]:
arr.reshape(3,3)

array([[ 1.52885439, -0.70541734,  0.782226  ],
       [ 0.23547317, -0.88726736, -1.88929099],
       [-0.6928929 , -0.27013184, -1.16523227]])

In [52]:
np.random.randint(5)

0

In [53]:
np.random.randint(1,100)

3

In [55]:
np.random.randint(1,100,10)

array([41, 20, 87, 32, 21, 88, 41, 38, 25,  9])

In [58]:
sd=np.random.randint(1,100,25)
print(sd)

[37 84 54 97 57  7 88 69 50 80 11 77 76 23 31 88 82 71 60 77 69 99  9 66
 83]


In [59]:
arr=sd.reshape(5,5)

In [60]:
print(arr)

[[37 84 54 97 57]
 [ 7 88 69 50 80]
 [11 77 76 23 31]
 [88 82 71 60 77]
 [69 99  9 66 83]]


In [62]:
arr.shape

(5, 5)

In [64]:
arr[2:4]

array([[11, 77, 76, 23, 31],
       [88, 82, 71, 60, 77]])

In [65]:
arr[2:2]

array([], shape=(0, 5), dtype=int32)

In [66]:
arr[2:]

array([[11, 77, 76, 23, 31],
       [88, 82, 71, 60, 77],
       [69, 99,  9, 66, 83]])

In [67]:
arr[2:,2:]

array([[76, 23, 31],
       [71, 60, 77],
       [ 9, 66, 83]])

In [68]:
arr[2:4,2:4]

array([[76, 23],
       [71, 60]])

In [69]:
arr

array([[37, 84, 54, 97, 57],
       [ 7, 88, 69, 50, 80],
       [11, 77, 76, 23, 31],
       [88, 82, 71, 60, 77],
       [69, 99,  9, 66, 83]])

In [70]:
arr[3:4,4:]

array([[77]])

In [71]:
arr[3:4,4:5]

array([[77]])

In [72]:
arr[3:4,1:2]

array([[82]])

In [74]:
arr.max()

99

In [75]:
arr.min()

7

In [77]:
np.sqrt(arr)

array([[6.08276253, 9.16515139, 7.34846923, 9.8488578 , 7.54983444],
       [2.64575131, 9.38083152, 8.30662386, 7.07106781, 8.94427191],
       [3.31662479, 8.77496439, 8.71779789, 4.79583152, 5.56776436],
       [9.38083152, 9.05538514, 8.42614977, 7.74596669, 8.77496439],
       [8.30662386, 9.94987437, 3.        , 8.1240384 , 9.11043358]])

In [78]:
arr

array([[37, 84, 54, 97, 57],
       [ 7, 88, 69, 50, 80],
       [11, 77, 76, 23, 31],
       [88, 82, 71, 60, 77],
       [69, 99,  9, 66, 83]])

In [79]:
arr[:,[1,4]]

array([[84, 57],
       [88, 80],
       [77, 31],
       [82, 77],
       [99, 83]])

In [80]:
arr[:,0::2]

array([[37, 54, 57],
       [ 7, 69, 80],
       [11, 76, 31],
       [88, 71, 77],
       [69,  9, 83]])

In [82]:
arr[0::2,:]

array([[37, 84, 54, 97, 57],
       [11, 77, 76, 23, 31],
       [69, 99,  9, 66, 83]])

In [83]:
arr

array([[37, 84, 54, 97, 57],
       [ 7, 88, 69, 50, 80],
       [11, 77, 76, 23, 31],
       [88, 82, 71, 60, 77],
       [69, 99,  9, 66, 83]])

In [84]:
arr[:,3]

array([97, 50, 23, 60, 66])

In [85]:
arr[2,:]

array([11, 77, 76, 23, 31])

In [86]:
bool_arr=arr>4

In [87]:
print(bool_arr)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [88]:
bool_arr=arr>30

In [89]:
print(bool_arr)

[[ True  True  True  True  True]
 [False  True  True  True  True]
 [False  True  True False  True]
 [ True  True  True  True  True]
 [ True  True False  True  True]]


In [90]:
arr[bool_arr]

array([37, 84, 54, 97, 57, 88, 69, 50, 80, 77, 76, 31, 88, 82, 71, 60, 77,
       69, 99, 66, 83])

In [5]:
import numpy as np

In [6]:
cric_data = np.loadtxt("C:\\Users\SAP\Desktop\cric_data.tsv",skiprows=1)

In [7]:
print(cric_data)

[[  0. 100.  78. 342.]
 [  1.  11.  62. 191.]
 [  2.   8.  85. 252.]
 [  3.  71.  24. 307.]
 [  4. 104.  17. 229.]
 [  5.  18. 104. 246.]
 [  6.   8.  76. 226.]
 [  7.  86.  74. 288.]
 [  8.  12.  60. 216.]
 [  9.  25.  90. 304.]
 [ 10.  56.   6. 272.]
 [ 11.  88.  69. 302.]
 [ 12. 147.  65. 312.]
 [ 13. 121. 146. 370.]
 [ 14.  99. 110. 362.]]


In [10]:
sachin=cric_data[:,1]
dravid=cric_data[:,2]
india=cric_data[:,3]

In [12]:
print("run by sachin is",sachin)
print("-----------------------")
print("run by dravid is",dravid)
print("-----------------------")
print("run by team india is",india)

run by sachin is [100.  11.   8.  71. 104.  18.   8.  86.  12.  25.  56.  88. 147. 121.
  99.]
-----------------------
run by dravid is [ 78.  62.  85.  24.  17. 104.  76.  74.  60.  90.   6.  69.  65. 146.
 110.]
-----------------------
run by team india is [342. 191. 252. 307. 229. 246. 226. 288. 216. 304. 272. 302. 312. 370.
 362.]


In [14]:
def stats(col):
    print("Mean score is",np.mean(col))
    print("Median score is",np.median(col))
    print("-------------------------------")
stats(sachin)

Mean score is 63.6
Median score is 71.0
-------------------------------


In [15]:
def stats(col):
    print("Mean score is",np.mean(col))
    print("Median score is",np.median(col))
    print("-------------------------------")
stats(sachin)
stats(dravid)
stats(india)

Mean score is 63.6
Median score is 71.0
-------------------------------
Mean score is 71.06666666666666
Median score is 74.0
-------------------------------
Mean score is 281.26666666666665
Median score is 288.0
-------------------------------


In [16]:
sc=np.count_nonzero(sachin>99)
dc=np.count_nonzero(dravid>99)
print("centuries score by sachin is-",sc)
print("centuries score by dravid is-",dc)

centuries score by sachin is- 4
centuries score by dravid is- 3


In [17]:
sachin.sum()

954.0

In [18]:
dravid.sum()

1066.0

In [19]:
sachin_cumsum=np.cumsum(sachin)
np.searchsorted(sachin_cumsum,800)

13

In [22]:
dravid_cumsum=np.cumsum(dravid)
np.searchsorted(dravid_cumsum,800)

12

In [1]:
import numpy as np

In [ ]:
list=[11,22,33,44,55]
list4=[]
x=int(input('enter the indedx'))
list4=list[x:]
list5=list[0:x]
print(list4+list5)